### ISSUE TITLE
Nested rsets was broken

### ISSUE THREAD

**Issue by NOX73** [rana/ora#96]
Nested rsets was broken after commit dac7aba843e7fe9a47adb3696466811691334328 
Did'n get the problem why it happend.

Here is the stack trace:

```
.....
ORA I 2016/06/20 14:26:07.875750 rset.go:900: E2S1S1S1S0 [Rset.open] 27. prec=0 scale=-127 => gct=OraF64
ORA I 2016/06/20 14:26:07.875794 rset.go:900: E2S1S1S1S0 [Rset.open] 29. prec=30 scale=0 => gct=N
ORA I 2016/06/20 14:26:07.875826 rset.go:900: E2S1S1S1S0 [Rset.open] 30. prec=30 scale=0 => gct=N
ORA I 2016/06/20 14:26:07.875860 rset.go:900: E2S1S1S1S0 [Rset.open] 31. prec=30 scale=0 => gct=N
ORA I 2016/06/20 14:26:07.875894 rset.go:900: E2S1S1S1S0 [Rset.open] 32. prec=0 scale=-127 => gct=OraF64
ORA I 2016/06/20 14:26:07.875923 rset.go:900: E2S1S1S1S0 [Rset.open] 33. prec=30 scale=0 => gct=N
ORA I 2016/06/20 14:26:07.876007 rset.go:886: E2S1S1S1S0 [Rset.Next]
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x90 pc=0x7fa22ca644fc]

runtime stack:
runtime.throw(0x9b91a0, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 18 [syscall, locked to thread]:
runtime.cgocall(0x78d940, 0xc8200cb208, 0x7fa200000000)
        /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8200cb1b8 sp=0xc8200cb188
git.restr.im/itv-rt/itv-api/vendor/github.com/rana/ora._Cfunc_OCIStmtFetch2(0x191bc80, 0x190f608, 0x200000080, 0x0, 0xc800000000)
        ??:0 +0x39 fp=0xc8200cb208 sp=0xc8200cb1b8
git.restr.im/itv-rt/itv-api/vendor/github.com/rana/ora.(*Rset).beginRow(0xc8202a6000, 0x0, 0x0)
        /go/src/git.restr.im/itv-rt/itv-api/vendor/github.com/rana/ora/rset.go:193 +0x565 fp=0xc8200cb328 sp=0xc8200cb208
git.restr.im/itv-rt/itv-api/vendor/github.com/rana/ora.(*Rset).Next(0xc8202a6000, 0x7fa2283c6000)
        /go/src/git.restr.im/itv-rt/itv-api/vendor/github.com/rana/ora/rset.go:263 +0xfc fp=0xc8200cb410 sp=0xc8200cb328
...
```

**Comment by tgulacsi** [comment]
Sorry, but what is an "inherited rset"?
Is it fixed in some commit, but wrong with dac7aba ?
What test have you used to bisect and find the broking commit?

Although that commit is huge, so a possible source of troubles...

Can you reproduce the problem?
Can you run your code with 
```
ulimit -v unlimited
env CGO_CFLAGS=-fsanitize=address CGO_LDFLAGS=-lasan <your program here>
```

? This address sanitizer should have catch the 0xb (SIGSEGV) errors.

**Comment by NOX73** [comment]
I meant nested rsets.
No, in the master branch it's still broken.
I've used my own application. It's been working before this commit, but it doesn't work after.

Here is stack trace:

```
ASAN:SIGSEGV
=================================================================
==20465==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f723f60f4fc sp 0x7f722ed6e060 bp 0x7f722ed6e0c0 T5)
    #0 0x7f723f60f4fb in kpcxc2r (/usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1+0x18bd4fb)
    #1 0x7f7240d672d7 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x582d7)
    #2 0x7f7240d65c0b (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x56c0b)
    #3 0x45fe84 in runtime.sigfwd (/tmp/go-build514681893/command-line-arguments/_obj/exe/main+0x45fe84)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 kpcxc2r
Thread T5 created by T3 here:
    #0 0x7f7240d32bba in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x23bba)
    #1 0x79a13e in _cgo_sys_thread_start /usr/local/go/src/runtime/cgo/gcc_linux_amd64.c:43
    #2 0x10c820505f9f (+0x205f9f)

Thread T3 created by T0 here:
    #0 0x7f7240d32bba in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x23bba)
    #1 0x79a13e in _cgo_sys_thread_start /usr/local/go/src/runtime/cgo/gcc_linux_amd64.c:43

==20465==ABORTING
exit status 1

```

**Comment by tgulacsi** [comment]
Okay, ASAN does not help.

Can you share anything about your code? A minimal working test would be the best, but maybe a description (what kind of tested rset?) could start us, too.

**Comment by tgulacsi** [comment]
Are you using PrepAndExe? As it closes the statement right after execution, it also closes the fresh Rset, too.
I've documented it harder in 8aa81bc.  Also, see `Test_cursor1_session` in `z_resultSet_session_test.go` - that test passes, so if it still fails on you, than please tweak that test till it reproduces the problem!

**Comment by NOX73** [comment]
No, we don't use `PrepAndExe`.

Our workflow looks like:

```golang

  env, err := ora.OpenEnv(nil)                           
  // defer env.Close()                                   
  if err != nil {                                        
    panic(err)                                           
  }                                                      
                                                         
  if logging {                                           
    ora.Cfg().Log.Logger = lg.Log                        
    ora.Cfg().Log.Rset.Next = true                       
  }                                                      
                                                         
  srvCfg := ora.NewSrvCfg()                              
                                                         
  srvCfg.Dblink = dbLink                                 
  srv, err := env.OpenSrv(srvCfg)                        
  // defer srv.Close()                                   
  if err != nil {                                        
    panic(err)                                           
  }                                                      
                                                         
  sesCfg := ora.NewSesCfg()                              
  sesCfg.Username = user                                 
  sesCfg.Password = pass                                 
  sesCfg.StmtCfg.Rset.SetNumberInt(ora.OraI64)                       
  sesCfg.StmtCfg.Rset.SetNumberFloat(ora.OraF64)                     
  sesCfg.StmtCfg.Rset.SetBinaryDouble(ora.OraF64)                    
  sesCfg.StmtCfg.Rset.SetBinaryFloat(ora.OraF64)                     
  sesCfg.StmtCfg.Rset.SetFloat(ora.OraF64)                           
  sesCfg.StmtCfg.Rset.SetDate(ora.OraT)                              
  sesCfg.StmtCfg.Rset.SetTimestamp(ora.OraT)                         
  sesCfg.StmtCfg.Rset.SetTimestampTz(ora.OraT)                       
  sesCfg.StmtCfg.Rset.SetTimestampLtz(ora.OraT)                      
  sesCfg.StmtCfg.Rset.SetChar1(ora.OraS)                             
  sesCfg.StmtCfg.Rset.SetVarchar(ora.OraS)                           
  sesCfg.StmtCfg.Rset.SetLong(ora.OraS)                              
                                                                     
  ses, err := srv.OpenSes(sesCfg)                               
                                     
  if err != nil {                                                    
    panic(err)                                                       
  }                                                                  

stmt, err := ses.Prep("CALL some_precedure(:1, :2, :3, :4, :5, :6)")  

if err != nil {                 
  return err                    
}                               
                                
rst := &ora.Rset{}             
                                
_, err = stmt.Exe(packageID.Value, regionID.Value, genresList.Value, from.Value, to.Value, rst)     
 
if err != nil {                 
  return err                    
}                       

  for rst.Next() { // here it fails                    

  }                                           

```

This flow fails only in cases when result contains nested rsets, otherwise, it works properly.

**Comment by tgulacsi** [comment]
Ooops, that was quite a lame error - sorry!
